name: Build Telegram API Server for Windows
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Chocolatey
      run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Visual Studio Build Tools
      run: choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional"

    - name: Install Dependencies
      run: choco install -y git cmake

    - name: Clone Repositories and Install Vcpkg
      run: |
        git clone --recursive https://github.com/tdlib/telegram-bot-api.git
        cd telegram-bot-api
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg.exe install gperf:x64-windows openssl:x64-windows zlib:x64-windows
        cd ..

    - name: Build the Project
      run: |
        cd telegram-bot-api
        Remove-Item build -Force -Recurse -ErrorAction SilentlyContinue
        mkdir build
        cd build
        cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=.. -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
        cmake --build . --target install --config Release

    - name: Move Built Files
      run: |
        mkdir -p ./build_output
        cp ./telegram-bot-api/bin/* ./build_output/

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add build_output/*
        git commit -m "Updated Windows binary"
        git push
