name: Build Telegram API Server for Windows
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install Dependencies
      run: |
        choco install -y git cmake
        git clone --recursive https://github.com/tdlib/telegram-bot-api.git
        cd telegram-bot-api
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add build/Release/telegram-bot-api.exe
        git commit -m "Updated Windows binary"
        git push
